###### Class launcher.powerkuy.growlauncher.R is created by jadx
###### Class launcher.powerkuy.growlauncher.R.anim is created by jadx
###### Class launcher.powerkuy.growlauncher.R.animator is created by jadx
###### Class launcher.powerkuy.growlauncher.R.array is created by jadx
###### Class launcher.powerkuy.growlauncher.R.attr is created by jadx
###### Class launcher.powerkuy.growlauncher.R.bool is created by jadx
###### Class launcher.powerkuy.growlauncher.R.color is created by jadx
###### Class launcher.powerkuy.growlauncher.R.dimen is created by jadx
###### Class launcher.powerkuy.growlauncher.R.drawable is created by jadx
###### Class launcher.powerkuy.growlauncher.R.font is created by jadx
###### Class launcher.powerkuy.growlauncher.R.id is created by jadx
###### Class launcher.powerkuy.growlauncher.R.integer is created by jadx
###### Class launcher.powerkuy.growlauncher.R.interpolator is created by jadx
###### Class launcher.powerkuy.growlauncher.R.layout is created by jadx
###### Class launcher.powerkuy.growlauncher.R.mipmap is created by jadx
###### Class launcher.powerkuy.growlauncher.R.plurals is created by jadx
###### Class launcher.powerkuy.growlauncher.R.raw is created by jadx
###### Class launcher.powerkuy.growlauncher.R.string is created by jadx
###### Class launcher.powerkuy.growlauncher.R.style is created by jadx
###### Class launcher.powerkuy.growlauncher.R.xml is created by jadx